name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Replace with your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Replace with your Node.js version

      # Install dependencies and build your project (if needed)
      - name: Install dependencies and build
        run: |
          npm install
          npm run build # Replace with your build command if applicable

      - name: Deploy to GitHub Pages
        #uses: actions/deploy-github-pages@v7
        uses : actions/runs/7080542212/job/19268583294
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Replace with the directory containing your built files
