name: Deploy to Production

on:
  push:
    branches:
      - main # Change to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Change to your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Install dependencies
        run: yarn install 

      - name: Build and deploy
        run: |
          # Your deployment command here
          # Example: npm run build && npm run deploy
          #node index.js 
          yarn start 
          

